### ISSUE TITLE
Look for specific API endpoint for an example data

### ISSUE THREAD

**Issue by yafimski** [ItamarShDev/my-gov-in-action#3]

**Comment by yafimski** [comment]
@ItamarShDev 
Look at
https://data.gov.il/dataset/2023-puf/resource/7e6194a3-cc27-4de6-91d4-025f26520617?inner_span=True

click on API לנתונים
on this page and see the api calls with GUID

We can do this per year, you can take years.. for example in the link there are 8832 rows in the table, it's a 'high-level' road accident overview without getting into all the column fields.

We can do 2017 to 2023
https://data.gov.il/dataset/?q=%D7%AA%D7%90%D7%95%D7%A0%D7%95%D7%AA+%D7%93%D7%A8%D7%9B%D7%99%D7%9D

Maybe also this for 2005-2011
https://data.gov.il/dataset/486/resource/519d46d5-7d82-4b6b-b838-1e9e427541ca?inner_span=True

**Comment by ItamarShDev** [comment]
https://excalidraw.com/#room=76300311aa15dd9916ac,SsP_lNJoJlDUU0kc_1GEmQ

https://docs.google.com/document/d/1MfKSsUaA7q_dy58eTAt82WaqbEilvYYwO4cs6_Yk82g/edit?usp=sharing
