### ISSUE TITLE
Basic Category Layout

### ISSUE THREAD

**Issue by yafimski** [ItamarShDev/my-gov-in-action#4]
- category icons
- every category needs its own router
- switching between categories needs a defined transition/animation
- each icon needs a selected state

**Comment by yafimski** [comment]
@ItamarShDev  please add relevant links from Remix or elsewhere for me to focus on for learning before I start attemping these tasks.

**Comment by ItamarShDev** [comment]
https://reactrouter.com/start/framework/routing

**Comment by ItamarShDev** [comment]
Notice that we moved to https://reactrouter.com/start/framework/routing because the libraries merged to one. 
the api should stay the same, but the link changed @yafimski
